name: Auto Release

on:
  workflow_dispatch:
  schedule:
    # At 01:00 (1 AM) every day
    - cron: '0 1 * * *'

env:
  COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
  API_AUTH_TOKEN_GITHUB: ${{ secrets.API_AUTH_TOKEN_GITHUB }}

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - run: npm install -g yarn
      - run: yarn --version

      - name: Install dependencies
        run: yarn

      - name: Bump patch version
        id: bump-version
        run: |
          VERSION=$(npm version patch --no-git-tag-version)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build assets
        run: yarn start

      - name: Bump version and commit build assets
        run: |
          git add data/ build/ package.json
          git commit -m "ci: update build assets (${{ steps.bump-version.outputs.version }})"
          git push

      - name: Publish NPM package
        run: npm run publish-token-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          tag_name: ${{ steps.bump-version.outputs.version }}
          generate_release_notes: true
          make_latest: true
